from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.sql import func
from database import Base


class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    name = Column(String, nullable=False)
    color = Column(String, default="#4A90E2")
    icon = Column(String, default="label")
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Task(Base):
    __tablename__ = "tasks"

    # ID is a UUID string generated by the Flutter client or admin panel
    id = Column(String, primary_key=True, index=True)
    title = Column(String, nullable=False)
    description = Column(Text, default="")
    date = Column(String, nullable=False)        # ISO 8601 datetime string
    start_time = Column(String, nullable=True)   # ISO 8601 datetime string
    end_time = Column(String, nullable=True)     # ISO 8601 datetime string
    status = Column(Integer, default=0)          # 0=pending, 1=inProgress, 2=completed
    mode = Column(Integer, default=0)            # 0=calendar, 1=smart
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=True)
    recurrence = Column(Text, nullable=True)     # JSON string
    is_carried_over = Column(Boolean, default=False)
    day_order = Column(Integer, default=0)
    parent_id = Column(String, nullable=True)
    is_recurring_parent = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
